services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data
    ports:
      - "5432:5432"
    volumes:
        - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8082:80"
  localisation-app:
    build: .
    container_name: ows-events-localisation
    command: python start.py
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/app